### PR TITLE
fixed some graphics issues

### LINKED ISSUE #26: Fix graphics glitches in cell rendering
When cell is surrounded with other obstacles (cells, borders), his rendering sometimes breaks and the cell starts drawing as a circle when he shouldn't or blinks for 1-2 frames.
image

### PR DESCRIPTION
**Pull request by david-d25**

### CODE REVIEW

**Comment by david-d25** [comment]
Unfortunately, weren't able to fix *all* issues, but most of them are fixed.

File: src/main/kotlin/com/devexperts/openhack2022/cell_sandbox/game/renderer/CellRenderer.kt [hunk 1]
```diff
@@ -161,36 +204,50 @@ class CellRenderer: Renderer<CellState> {
...
-        if (obstacles.size > 1) {
-            val a = obstacles.first().first
-            val b = obstacles.last().first
-            if ((target.center to b).angle() > (target.center to a).angle()) {
-                val intersection = testLinesIntersection(obstacles.last(), obstacles.first())
-                if (intersection != null) {
-                    obstacles[0] = obstacles[0].copy(first = intersection)
-                    obstacles[obstacles.size - 1] = obstacles[obstacles.size - 1].copy(second = intersection)
+            val intersection = testLinesIntersection(obstacle, next)
+            if (intersection != null) {
```
Comment (olegthelilfix) [inline src/main/kotlin/com/devexperts/openhack2022/cell_sandbox/game/renderer/CellRenderer.kt]: it would be better to put this 3 if's to one

File: src/main/kotlin/com/devexperts/openhack2022/cell_sandbox/game/renderer/CellRenderer.kt [hunk 2]
```diff
@@ -20,6 +28,8 @@ class CellRenderer: Renderer<CellState> {
         context.save()
```
Comment (olegthelilfix) [inline src/main/kotlin/com/devexperts/openhack2022/cell_sandbox/game/renderer/CellRenderer.kt:28]: Function render look really giant, so can we try to split it?

**Review by olegthelilfix — CHANGES_REQUESTED** [review]

**Review by olegthelilfix — APPROVED** [review]
