### PR TITLE
fixed NPE

### LINKED ISSUE #30: Cell split algorithm causes NPE
Sometimes, when there are a lot of cells on the area, cell split algorithm causes NPE:
`Exception in thread "Thread-3" java.lang.NullPointerException
	at openhack2022y.cell_sandbox/com.devexperts.openhack2022.cell_sandbox.game.updater.CellUpdater.split(CellUpdater.kt:208)
	at openhack2022y.cell_sandbox/com.devexperts.openhack2022.cell_sandbox.game.updater.CellUpdater.update(CellUpdater.kt:51)
	at openhack2022y.cell_sandbox/com.devexperts.openhack2022.cell_sandbox.game.World.update(World.kt:75)
	at openhack2022y.cell_sandbox/com.devexperts.openhack2022.cell_sandbox.App.start$lambda$0(App.kt:61)
	at java.base/java.lang.Thread.run(Thread.java:834)`

Area state at the moment:
[world.area.txt](https://github.com/david-d25/cell-sandbox/files/9818929/world.area.txt)

Area screenshot at the moment:
image

### PR DESCRIPTION
**Pull request by david-d25**

### CODE REVIEW

File: src/main/kotlin/com/devexperts/openhack2022/cell_sandbox/game/World.kt [hunk 1]
```diff
@@ -55,6 +55,12 @@ class World (val settings: WorldSettings) {
         area.borders.remove(wo.id)
         area.food.remove(wo.id)
         area.cells.remove(wo.id)
+
+        if (wo is CellState) {
+            wo.connections.keys.forEach { id ->
+                area.cells[id]!!.connections = area.cells[id]!!.connections.filterKeys { it != wo.id }
```
Comment (olegthelilfix) [inline src/main/kotlin/com/devexperts/openhack2022/cell_sandbox/game/World.kt]: I suppose, it would better to implement that code block like that

>                 area.cells[id]?.let { cellState ->
>                     cellState.connections = cellState.connections.filterKeys { it != wo.id }
>                 }
Cuz we don't throw NPE in worth case.

**Review by olegthelilfix — CHANGES_REQUESTED** [review]

**Review by olegthelilfix — APPROVED** [review]
